
package eu.glowacki.jaxws.client.onewayrobust.proxy;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IOneWayRobust", targetNamespace = "http://glowacki.eu/one-way-robust")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IOneWayRobust {


    /**
     * 
     * @param arg0
     * @throws ServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "trigger", targetNamespace = "http://glowacki.eu/one-way-robust", className = "eu.glowacki.jaxws.client.onewayrobust.proxy.Trigger")
    @ResponseWrapper(localName = "triggerResponse", targetNamespace = "http://glowacki.eu/one-way-robust", className = "eu.glowacki.jaxws.client.onewayrobust.proxy.TriggerResponse")
    @Action(input = "http://glowacki.eu/one-way-robust/IOneWayRobust/triggerRequest", output = "http://glowacki.eu/one-way-robust/IOneWayRobust/triggerResponse", fault = {
        @FaultAction(className = ServiceException_Exception.class, value = "http://glowacki.eu/one-way-robust/IOneWayRobust/trigger/Fault/ServiceException")
    })
    public void trigger(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "triggerNotRobust", targetNamespace = "http://glowacki.eu/one-way-robust", className = "eu.glowacki.jaxws.client.onewayrobust.proxy.TriggerNotRobust")
    @ResponseWrapper(localName = "triggerNotRobustResponse", targetNamespace = "http://glowacki.eu/one-way-robust", className = "eu.glowacki.jaxws.client.onewayrobust.proxy.TriggerNotRobustResponse")
    @Action(input = "http://glowacki.eu/one-way-robust/IOneWayRobust/triggerNotRobustRequest", output = "http://glowacki.eu/one-way-robust/IOneWayRobust/triggerNotRobustResponse")
    public void triggerNotRobust(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
