package eu.glowacki.jaxws.implementation.addressing;

import eu.glowacki.jaxws.api.addressing.AddressingException;
import eu.glowacki.jaxws.api.addressing.IAddressing;
import jakarta.jws.WebService;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.Endpoint;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.soap.Addressing;

import java.util.logging.Logger;

@WebService( //
		name = "IAddressing", //
		targetNamespace = "http://glowacki.eu/addressing" //
)
@Addressing( //
		enabled = true, //
		required = true //
)
public final class AddressingImpl implements IAddressing {

	private static final Logger LOGGER = Logger.getAnonymousLogger();

	public static void main(String... args) {
		Endpoint.publish(IAddressing.URI, new AddressingImpl());
		LOGGER.info("SERVICE STARTED");
	}

	// @WebMethod(action = "http://glowacki.eu/addressing")
	/**
	 * @Action annotation enables specifying custom identification of messages
	 *         instead of relying on autogenerated names
	 */
	@Action( //
			input = "http://glowacki.eu/addressing/AddressingRequest", //
			output = "http://glowacki.eu/addressing/AddressingResponse", //
			fault = { //
					@FaultAction(className = AddressingException.class, value = "http://glowacki.eu/addressing/AddressException") //
			} //
	)
	public String addressing(String request) throws AddressingException {
		String response = String.format("(ADDRESSING) %s", request);
		LOGGER.info(response);
		return response;
	}
}