package eu.glowacki;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2023-05-19T18:34:45.688+02:00
 * Generated source version: 3.5.2
 *
 */
@WebServiceClient(name = "EchoImpl",
                  wsdlLocation = "classpath:IEcho.wsdl",
                  targetNamespace = "http://glowacki.eu")
public class EchoImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://glowacki.eu", "EchoImpl");
    public final static QName BasicHttpBindingIEcho = new QName("http://glowacki.eu", "BasicHttpBinding_IEcho");
    static {
        URL url = EchoImpl.class.getClassLoader().getResource("IEcho.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(EchoImpl.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:IEcho.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EchoImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EchoImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EchoImpl() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EchoImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EchoImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EchoImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IEcho
     */
    @WebEndpoint(name = "BasicHttpBinding_IEcho")
    public IEcho getBasicHttpBindingIEcho() {
        return super.getPort(BasicHttpBindingIEcho, IEcho.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEcho
     */
    @WebEndpoint(name = "BasicHttpBinding_IEcho")
    public IEcho getBasicHttpBindingIEcho(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIEcho, IEcho.class, features);
    }

}
