
package eu.glowacki.jaxws.client.wcf.proxy;

import jakarta.xml.ws.*;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculatorImpl", targetNamespace = "http://glowacki.eu", wsdlLocation = "http://localhost:8080?wsdl")
public class CalculatorImpl
    extends Service
{

    private final static URL CALCULATORIMPL_WSDL_LOCATION;
    private final static WebServiceException CALCULATORIMPL_EXCEPTION;
    private final static QName CALCULATORIMPL_QNAME = new QName("http://glowacki.eu", "CalculatorImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATORIMPL_WSDL_LOCATION = url;
        CALCULATORIMPL_EXCEPTION = e;
    }

    public CalculatorImpl() {
        super(__getWsdlLocation(), CALCULATORIMPL_QNAME);
    }

    public CalculatorImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATORIMPL_QNAME, features);
    }

    public CalculatorImpl(URL wsdlLocation) {
        super(wsdlLocation, CALCULATORIMPL_QNAME);
    }

    public CalculatorImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATORIMPL_QNAME, features);
    }

    public CalculatorImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICalculator
     */
    @WebEndpoint(name = "BasicHttpBinding_ICalculator")
    public ICalculator getBasicHttpBindingICalculator() {
        return super.getPort(new QName("http://glowacki.eu", "BasicHttpBinding_ICalculator"), ICalculator.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns ICalculator
     */
    @WebEndpoint(name = "BasicHttpBinding_ICalculator")
    public ICalculator getBasicHttpBindingICalculator(WebServiceFeature... features) {
        return super.getPort(new QName("http://glowacki.eu", "BasicHttpBinding_ICalculator"), ICalculator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATORIMPL_EXCEPTION!= null) {
            throw CALCULATORIMPL_EXCEPTION;
        }
        return CALCULATORIMPL_WSDL_LOCATION;
    }

}
