
package eu.glowacki.jaxws.client.bigdata.mtom.proxy;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IBigDataMTOM", targetNamespace = "http://glowacki.eu/big-data/mtom")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IBigDataMTOM {


    /**
     * 
     * @return
     *     returns eu.glowacki.jaxws.client.bigdata.mtom.proxy.BigData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://glowacki.eu/big-data/mtom", className = "eu.glowacki.jaxws.client.bigdata.mtom.proxy.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://glowacki.eu/big-data/mtom", className = "eu.glowacki.jaxws.client.bigdata.mtom.proxy.GetResponse")
    @Action(input = "http://glowacki.eu/big-data/mtom/IBigDataMTOM/getRequest", output = "http://glowacki.eu/big-data/mtom/IBigDataMTOM/getResponse")
    public BigData get();

}
